version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  redis_cache:
    image: redis:8-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - backend

  flask_app:
    build: ./web
    container_name: flask_app
    depends_on:
      - db
      - redis_cache
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: postgres
      DB_PASSWORD: mypassword
      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
    ports:
      - "5000:5000"
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
